# GitLab CI for Django/Python
# Copy to: .gitlab-ci.yml
#
# Features:
# - YAML linting
# - Parallel lint + test
# - PostgreSQL service
# - Poetry dependency management
# - Coverage reporting
# - Type checking with mypy

stages:
  - lint
  - test
  - build
  - deploy

# YAML lint - validates all YAML files
yaml-lint:
  stage: lint
  image: python:3.12-slim
  before_script:
    - pip install yamllint --quiet
  script:
    - yamllint -d relaxed . || true
    - yamllint --strict .gitlab-ci.yml
  allow_failure: true

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/test_db"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

.python:
  image: python:3.12
  before_script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --no-interaction
  cache:
    key: ${CI_COMMIT_REF_SLUG}-python
    paths:
      - .venv/
      - .pip-cache/

lint:
  extends: .python
  stage: test
  script:
    - poetry run black --check .
    - poetry run ruff check .
  allow_failure: true

typecheck:
  extends: .python
  stage: test
  script:
    - poetry run mypy .
  allow_failure: true

test:
  extends: .python
  stage: test
  services:
    - postgres:15
  variables:
    DJANGO_SETTINGS_MODULE: config.settings.test
  script:
    - poetry run python manage.py migrate --noinput
    - poetry run pytest --cov=. --cov-report=term-missing --cov-report=xml
  coverage: '/TOTAL.*\s+(\d+%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

security:
  image: python:3.12
  stage: test
  script:
    - pip install pip-audit
    - pip-audit -r requirements.txt || pip-audit
  allow_failure: true

# Optional: Build Docker image
# build:
#   stage: build
#   image: docker:24
#   services:
#     - docker:24-dind
#   needs: [test]
#   script:
#     - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#   only:
#     - main
