# GitLab CI for Laravel
# Copy to: .gitlab-ci.yml
#
# Features:
# - YAML linting
# - Parallel lint + test
# - MySQL service
# - Caching
# - Security scanning
# - Coverage reporting

stages:
  - lint
  - prepare
  - test
  - build
  - deploy

# YAML lint - validates all YAML files
yaml-lint:
  stage: lint
  image: python:3.12-slim
  before_script:
    - pip install yamllint --quiet
  script:
    - yamllint -d relaxed . || true
    - yamllint --strict .gitlab-ci.yml
  allow_failure: true

variables:
  MYSQL_DATABASE: testing
  MYSQL_ROOT_PASSWORD: secret
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_DATABASE: testing
  DB_USERNAME: root
  DB_PASSWORD: secret

# Base template - extend this
.php:
  image: php:8.3-cli
  before_script:
    - apt-get update && apt-get install -y git zip unzip libpq-dev libzip-dev libpng-dev
    - docker-php-ext-install pdo pdo_mysql zip gd
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

install:
  extends: .php
  stage: prepare
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour

lint:
  extends: .php
  stage: test
  needs: [install]
  script:
    - vendor/bin/pint --test
  allow_failure: true

phpstan:
  extends: .php
  stage: test
  needs: [install]
  script:
    - vendor/bin/phpstan analyse --memory-limit=1G
  allow_failure: true

test:
  extends: .php
  stage: test
  needs: [install]
  services:
    - mysql:8.0
  script:
    - cp .env.testing .env
    - php artisan key:generate
    - php artisan migrate --force
    - php artisan test --parallel --coverage-text
  coverage: '/Lines:\s*(\d+\.\d+)%/'

security:
  stage: test
  image: php:8.3-cli
  needs: [install]
  script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar audit --format=plain
  allow_failure: true

# Optional: Build for production
# build:
#   extends: .php
#   stage: build
#   needs: [test]
#   script:
#     - composer install --no-dev --optimize-autoloader
#     - php artisan config:cache
#     - php artisan route:cache
#     - php artisan view:cache
#   artifacts:
#     paths:
#       - vendor/
#       - bootstrap/cache/
#     expire_in: 1 week
